# Generated by Django 4.2.2 on 2023-06-22 00:38

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='LikedMovies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Actors', models.TextField()),
                ('Awards', models.CharField(max_length=255)),
                ('BoxOffice', models.CharField(max_length=255)),
                ('Country', models.CharField(max_length=100)),
                ('Director', models.CharField(max_length=255)),
                ('DVD', models.CharField(max_length=255)),
                ('Genre', models.CharField(max_length=255)),
                ('imdbID', models.CharField(max_length=20)),
                ('imdbRating', models.CharField(max_length=20)),
                ('imdbVotes', models.CharField(max_length=20)),
                ('Language', models.CharField(max_length=100)),
                ('Metascore', models.IntegerField(null=True)),
                ('Plot', models.TextField()),
                ('Poster', models.URLField()),
                ('Production', models.CharField(max_length=255)),
                ('Rated', models.CharField(max_length=50)),
                ('Ratings', models.JSONField()),
                ('Released', models.CharField(max_length=255)),
                ('Response', models.BooleanField()),
                ('Runtime', models.CharField(max_length=50)),
                ('Title', models.CharField(max_length=255)),
                ('Type', models.CharField(max_length=50)),
                ('Website', models.URLField(null=True)),
                ('Writer', models.CharField(max_length=255)),
                ('Year', models.CharField(max_length=4)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='liked_movies',
            field=models.ManyToManyField(related_name='users', to='movies_list.likedmovies'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
    ]
