# Generated by Django 4.2.2 on 2023-06-22 02:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies_list', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='likedmovies',
            name='user',
        ),
        migrations.RemoveField(
            model_name='user',
            name='liked_movies',
        ),
    ]
