# Generated by Django 4.2.2 on 2023-06-22 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies_list', '0003_alter_likedmovies_metascore'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likedmovies',
            name='Poster',
            field=models.CharField(max_length=255),
        ),
    ]
